blank_issues_enabled: true
contact_links:
  - name: Our forum 💬
    url: https://forum.openwrt.org/
    about: Ask and answer questions here.
  - name: Our website 🌐🔗
    url: https://openwrt.org/
    about: The main website.
  - name: New Table of hardware 💻⚙️
    url: https://toh.openwrt.org/
    about: Find your hardware platform here (faster, more filtering options).
  - name: Old Table of hardware 💻⚙️
    url: https://openwrt.org/toh/start
    about: Find your hardware platform here (slower, fewer filtering options).
  - name: JS API docs 📝♨️
    url: https://openwrt.github.io/luci/jsapi/
